services:
  db_service:
    image: postgres:15.0-alpine
    container_name: db_service
    env_file:
      - ./src/.env
    volumes:
      - db_service_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  

volumes:
  db_service_data:
 
