# Generated by Django 4.2.1 on 2023-10-31 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла')),
                ('file_path', models.CharField(db_index=True, max_length=500, verbose_name='Путь к файлу')),
                ('description', models.TextField(blank=True, verbose_name='комментарий')),
                ('count_download', models.BigIntegerField(default=0, verbose_name='количество скачиваний')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='владелец файла')),
            ],
            options={
                'verbose_name': 'user_file',
                'verbose_name_plural': 'user_file',
                'db_table': 'user_file',
            },
        ),
        migrations.CreateModel(
            name='SharedUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_url', models.CharField(db_index=True, max_length=500, verbose_name='Короткая ссылка на расшаренный файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filestorage.userfile')),
            ],
            options={
                'verbose_name': 'Публичные файлы',
                'verbose_name_plural': 'Публичные файлы',
                'db_table': 'shared_url',
            },
        ),
    ]
