# Generated by Django 4.2.1 on 2023-10-31 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0002_userfile_sharedurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='owner',
        ),
        migrations.AddField(
            model_name='userfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец файла'),
            preserve_default=False,
        ),
    ]
