# Generated by Django 4.2.1 on 2023-10-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0003_remove_userfile_owner_userfile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfile',
            options={'verbose_name': 'Список файлов пользователей', 'verbose_name_plural': 'Список файлов пользователей'},
        ),
    ]
