# Generated by Django 4.2.1 on 2023-10-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0004_alter_userfile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedurl',
            name='short_url',
        ),
    ]
