# Generated by Django 4.2.1 on 2023-11-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0005_remove_sharedurl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='downloaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
